user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"


admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin

category:
    resource: "@CategoryBundle/Resources/config/routing.yml"
    prefix:   /category

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

product:
    resource: "@ProductBundle/Resources/config/routing.yml"
    prefix:   /product

catalog:
    resource: "@CatalogBundle/Resources/config/routing.yml"
    prefix:   /
