services:
    admin.category:
        class: CategoryBundle\Admin\CategoryAdmin
        arguments: [~, CategoryBundle\Entity\Category, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: category.group
              label: category.label
              label_catalogue: CategoryBundle
