services:
    # ...
    admin.product:
        class: ProductBundle\Admin\ProductAdmin
        arguments: [~, ProductBundle\Entity\Product, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Product", label: Product }