services:
    entity.category:
              class: CategoryBundle\Entity\Category

    admin.category:
        class: CategoryBundle\Admin\CategoryAdmin
        arguments: [~, CategoryBundle\Entity\Category, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: category.group
              label: category.label
              label_catalogue: CategoryBundle

    manage.category:
        class: CategoryBundle\Services\ManageCategory
        arguments: ['@entity.category', '@doctrine.orm.entity_manager']