<?php

namespace OrderBundle\Repository;

/**
 * QuoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuoteRepository extends \Doctrine\ORM\EntityRepository
{
    public function getQuoteProduct(){}
    
    public function getSumPriceProduct(){}
    
    public function productQuantity(){}
    
    public function addQuoteProduct(){}
    
    public function deleteQuoteProduct(){}
}
