services:
    admin.category:
            class: CategoryBundle\Admin\CategoryAdmin
            arguments: [~, CategoryBundle\Entity\Category, ~]
            tags:
                - { name: sonata.admin, manager_type: orm, group: "Category", label: Category }