services:
    admin.product:
        class: ProductBundle\Admin\ProductAdmin
        arguments: [~, ProductBundle\Entity\Product, ~]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: product.group
              label: product.label
              label_catalogue: ProductBundle