order_homepage:
    path:     /index
    defaults: { _controller: OrderBundle:Order:index }

buy_product:
    path:     /buy/{name}
    defaults: { _controller: OrderBundle:Order:createQuote}

delete_product:
    path:     /delete/{id}
    defaults: { _controller: OrderBundle:Order:deleteQuote}

confirm_order:
    path:     /confirm/{id}
    defaults: { _controller: OrderBundle:Order:confirm}