order_homepage:
    path:     /index
    defaults: { _controller: OrderBundle:Order:index }

buy_product:
    path:     /buy/{name}
    defaults: { _controller: OrderBundle:Order:addProduct}

delete_product:
    path:     /delete/{id}
    defaults: { _controller: OrderBundle:Order:delete}

confirm_order:
    path:     /confirm
    defaults: { _controller: OrderBundle:Order:confirm}