services:
    order.entity:
        class: OrderBundle\Entity\Orders

    quote.entity:
        class: OrderBundle\Entity\Quote

    class.metadata:
          class: Doctrine\ORM\Mapping\ClassMetadata
          autowire: true
          arguments: ['@order.entity']

    order.repository:
          class: OrderBundle\Repository\OrdersRepository
          arguments: ['@doctrine.orm.entity_manager', '@class.metadata']

    quote.repository:
          class: OrderBundle\Repository\QuoteRepository
          arguments: ['@doctrine.orm.entity_manager', '@class.metadata']

    order.flash_listener:
          class: OrderBundle\EventListener\FlashListener
          arguments: ['@session']
          tags:
              - { name: kernel.event_subscriber }