<?php

namespace ProductBundle\Repository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Get all exists products
     *
     * @return array
     */
    public function getAllProduct()
    {
        $query = $this->createQueryBuilder('p')
            ->orderBy('p.id','DESC')
            ->getQuery();
        
        return $query->getResult();
    }

    /**
     * Get the last $count elements
     *
     * @param $count
     * @return array
     */
    public function getLastProduct($count)
    {
        $query = $this->createQueryBuilder('p')
            ->orderBy('p.id','DESC')
            ->setMaxResults($count)
            ->getQuery();
        
        return $query->getResult();
    }

    /**
     * Get products by select category
     * 
     * @param $category
     * @return mixed
     */
    public function getProductByCategory($category)
    {
        $em = $this->getEntityManager();
        
        $category = $em->getRepository('CategoryBundle:Category')->getCategoryByName($category);

        return $category->getProduct();
    }
}   
